'use server'

import { createClient } from '@/utils/supabase/server'

export async function getProjectFiles(projectId: string) {
  try {
    const supabase = await createClient()
    const { data: { user } } = await supabase.auth.getUser()

    if (!user) {
      return { error: 'Unauthorized' }
    }

    const { data: project, error } = await supabase
      .from('projects')
      .select('code_content, name')
      .eq('id', projectId)
      .eq('user_id', user.id)
      .single()

    if (error || !project) {
      return { error: 'Project not found' }
    }

    let files: Record<string, string> = {}
    
    try {
      files = JSON.parse(project.code_content || '{}')
    } catch (e) {
      return { error: 'Invalid project data' }
    }

    // Ensure critical files exist
    if (!files['/app/layout.tsx']) {
      files['/app/layout.tsx'] = `import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: '${project.name}',
  description: 'Generated by AI',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  )
}`
    }

    if (!files['/app/page.tsx']) {
      files['/app/page.tsx'] = `export default function Home() {
  return (
    <main className="flex min-h-screen flex-col items-center justify-between p-24">
      <h1 className="text-4xl font-bold">Welcome to ${project.name}</h1>
    </main>
  )
}`
    }

    // Add essential Next.js files if they don't exist
    const essentialFiles: Record<string, string> = {
      '/package.json': JSON.stringify({
        name: project.name.toLowerCase().replace(/\s+/g, '-'),
        version: '0.1.0',
        private: true,
        scripts: {
          dev: 'next dev',
          build: 'next build',
          start: 'next start',
          lint: 'next lint'
        },
        dependencies: {
          'react': '^18.2.0',
          'react-dom': '^18.2.0',
          'next': '^14.0.0',
          'lucide-react': '^0.263.1',
          'framer-motion': '^10.16.0',
          'clsx': '^2.0.0',
          'tailwind-merge': '^2.0.0'
        },
        devDependencies: {
          'typescript': '^5.0.0',
          '@types/node': '^20.0.0',
          '@types/react': '^18.2.0',
          '@types/react-dom': '^18.2.0',
          'tailwindcss': '^3.3.0',
          'postcss': '^8.4.0',
          'autoprefixer': '^10.4.0',
          'eslint': '^8.0.0',
          'eslint-config-next': '^14.0.0'
        }
      }, null, 2),
      
      '/next.config.js': `/** @type {import('next').NextConfig} */
const nextConfig = {
  typescript: {
    ignoreBuildErrors: true,
  },
  eslint: {
    ignoreDuringBuilds: true,
  },
}

module.exports = nextConfig
`,
      
      '/tsconfig.json': JSON.stringify({
        compilerOptions: {
          target: 'ES2017',
          lib: ['dom', 'dom.iterable', 'esnext'],
          allowJs: true,
          skipLibCheck: true,
          strict: true,
          noEmit: true,
          esModuleInterop: true,
          module: 'esnext',
          moduleResolution: 'bundler',
          resolveJsonModule: true,
          isolatedModules: true,
          jsx: 'preserve',
          incremental: true,
          plugins: [{ name: 'next' }],
          paths: { '@/*': ['./*'] }
        },
        include: ['next-env.d.ts', '**/*.ts', '**/*.tsx', '.next/types/**/*.ts'],
        exclude: ['node_modules']
      }, null, 2),
      
      '/tailwind.config.ts': `import type { Config } from 'tailwindcss'

const config: Config = {
  content: [
    './pages/**/*.{js,ts,jsx,tsx,mdx}',
    './components/**/*.{js,ts,jsx,tsx,mdx}',
    './app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      colors: {
        background: 'var(--background)',
        foreground: 'var(--foreground)',
        textPrimary: 'var(--text-primary)',
        textSecondary: 'var(--text-secondary)',
        primary: {
          DEFAULT: '#4f46e5',
          foreground: '#ffffff',
        },
        secondary: {
          DEFAULT: '#f3f4f6',
          foreground: '#1f2937',
        },
      },
    },
  },
  plugins: [],
}
export default config
`,
      
      '/postcss.config.js': `module.exports = {
  plugins: {
    tailwindcss: {},
    autoprefixer: {},
  },
}
`,
      
      '/.gitignore': `# dependencies
/node_modules
/.pnp
.pnp.js

# testing
/coverage

# next.js
/.next/
/out/

# production
/build

# misc
.DS_Store
*.pem

# debug
npm-debug.log*
yarn-debug.log*
yarn-error.log*

# local env files
.env*.local

# vercel
.vercel

# typescript
*.tsbuildinfo
next-env.d.ts
`,
      
      '/app/globals.css': `@tailwind base;
@tailwind components;
@tailwind utilities;

:root {
  --background: #ffffff;
  --foreground: #000000;
  --text-primary: #111827;
  --text-secondary: #4b5563;
}

@media (prefers-color-scheme: dark) {
  :root {
    --background: #0a0a0a;
    --foreground: #ffffff;
    --text-primary: #f9fafb;
    --text-secondary: #9ca3af;
  }
}

body {
  color: var(--text-primary);
  background: var(--background);
}
`,
      '/README.md': `# ${project.name}

This is a [Next.js](https://nextjs.org/) project generated with AI.

## Getting Started

First, install dependencies:

\`\`\`bash
npm install
# or
yarn install
# or
pnpm install
\`\`\`

Then, run the development server:

\`\`\`bash
npm run dev
# or
yarn dev
# or
pnpm dev
\`\`\`

Open [http://localhost:3000](http://localhost:3000) with your browser to see the result.

## Deploy on Vercel

The easiest way to deploy your Next.js app is to use the [Vercel Platform](https://vercel.com/new).

Check out the [Next.js deployment documentation](https://nextjs.org/docs/deployment) for more details.
`
    }

    // Merge essential files with generated files
    const allFiles = { ...essentialFiles, ...files }

    // Fix imports in layout.tsx (AI sometimes generates ../globals.css which is wrong for app/layout.tsx)
    if (allFiles['/app/layout.tsx']) {
      allFiles['/app/layout.tsx'] = allFiles['/app/layout.tsx'].replace(
        /import\s+['"]\.\.\/globals\.css['"]/g,
        "import './globals.css'"
      )
    }

    // Auto-fix "use client" for files using hooks
    Object.keys(allFiles).forEach(path => {
      if (path.endsWith('.tsx') || path.endsWith('.ts') || path.endsWith('.jsx') || path.endsWith('.js')) {
        const content = allFiles[path]
        // Check for React hooks or event handlers which imply client-side logic
        const hasHooks = /use(State|Effect|Ref|Context|Reducer|Callback|Memo|LayoutEffect|ImperativeHandle|DebugValue|DeferredValue|Transition|Id|SyncExternalStore|InsertionEffect)/.test(content)
        const hasEventHandlers = /onClick|onChange|onSubmit|onMouseEnter|onMouseLeave/.test(content)
        const hasFramerMotion = content.includes('framer-motion')
        const hasUseClient = content.includes("'use client'") || content.includes('"use client"')
        
        if ((hasHooks || hasEventHandlers || hasFramerMotion) && !hasUseClient) {
           allFiles[path] = `'use client'\n${content}`
        }
      }
    })

    // Deduplicate structural components (Header, Navbar, Footer) if they appear in both layout and page
    if (allFiles['/app/layout.tsx'] && allFiles['/app/page.tsx']) {
        const layoutContent = allFiles['/app/layout.tsx'];
        let pageContent = allFiles['/app/page.tsx'];
        
        ['Header', 'Navbar', 'Footer'].forEach(component => {
            // Check if component is used in layout (e.g. <Header /> or <Header>)
            if (layoutContent.includes(`<${component}`)) {
                // If also used in page, remove it from page to prevent double rendering
                if (pageContent.includes(`<${component}`)) {
                    // Remove self-closing tags <Header />
                    pageContent = pageContent.replace(new RegExp(`<${component}[^>]*\\/?>`, 'g'), '');
                    // Remove opening/closing tags <Header>...</Header>
                    pageContent = pageContent.replace(new RegExp(`<${component}[^>]*>[\\s\\S]*?<\\/${component}>`, 'g'), '');
                }
            }
        });
        allFiles['/app/page.tsx'] = pageContent;
    }

    return { success: true, files: allFiles, projectName: project.name }
  } catch (error: any) {
    console.error('Error getting project files:', error)
    return { error: error.message || 'Failed to get project files' }
  }
}
